version: '3.8'

services:
  db:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/Test1234
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  api:
    image: express-neo4j-example
    container_name: express-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NEO4J_URI=bolt://db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=Test1234

volumes:
  neo4j_data: